---
- ansible.builtin.copy:
    src: bashrc.txt
    dest: /home/suap/.bashrc
    owner: suap
    group: suap
    mode: '0644'

- ansible.builtin.copy:
    src: profile.txt
    dest: /home/suap/.profile
    owner: suap
    group: suap
    mode: '0644'
