---
- ansible.builtin.copy:
    src: exports.vagrant.txt
    dest: /etc/exports
    owner: root
    group: root
    mode: '0644'
  when: (_test is defined)

- ansible.builtin.copy:
    src: exports.machine.txt
    dest: /etc/exports
    owner: root
    group: root
    mode: '0644'
  when: (_test is undefined)
