---
- ansible.builtin.copy:
    src: hosts.vagrant.txt
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'
  when: (_test is defined)

- ansible.builtin.copy:
    src: hosts.machine.txt
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'
  when: (_test is undefined)
