---
- ansible.builtin.copy:
    src: deploy-suap.sh
    dest: /usr/local/bin
    mode: '0755'

- ansible.builtin.copy:
    src: settings.vagrant.py
    dest: /var/opt/suap/suap/settings.py
    mode: '0644'
  when: (_test is defined)
