---
- ansible.posix.mount:
    src: 'suap-prod-nfs:/media/suap/deploy/media'
    path: '/var/opt/suap/deploy/media'
    fstype: nfs
    opts: 'rw,sync,hard,intr,rsize=1492,wsize=1492'
    state: mounted

- ansible.posix.mount:
    src: 'suap-prod-nfs:/media/suap/deploy/sessions'
    path: '/var/opt/suap/deploy/sessions'
    fstype: nfs
    opts: 'rw,sync,hard,intr,rsize=1492,wsize=1492'
    state: mounted

- ansible.posix.mount:
    src: 'suap-prod-nfs:/media/suap/upload'
    path: '/var/opt/suap/upload'
    fstype: nfs
    opts: 'rw,sync,hard,intr,rsize=1492,wsize=1492'
    state: mounted

- ansible.posix.mount:
    src: 'suap-prod-nfs:/media/suap/logs'
    path: '/opt/suap/logs'
    fstype: nfs
    opts: 'rw,sync,hard,intr,rsize=1492,wsize=1492'
    state: mounted

- ansible.posix.mount:
    src: 'suap-prod-nfs:/media/suap/static'
    path: '/opt/suap/static'
    fstype: nfs
    opts: 'rw,sync,hard,intr,rsize=1492,wsize=1492'
    state: mounted
